services:
  - type: web
    name: yuki-youtube-slim
    env: python3
    region: Oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --port $PORT --host 0.0.0.0 main:app"
